package protocol;
// Generated by proto2javame, Sat Jan 09 02:23:17 CST 2016.

import java.io.IOException;
import java.io.InputStream;


import net.jarlehansen.protobuf.javame.input.InputReader;
import net.jarlehansen.protobuf.javame.input.DelimitedInputStream;
import net.jarlehansen.protobuf.javame.input.DelimitedSizeUtil;
import net.jarlehansen.protobuf.javame.ComputeSizeUtil;
import net.jarlehansen.protobuf.javame.output.OutputWriter;
import net.jarlehansen.protobuf.javame.AbstractOutputWriter;
import net.jarlehansen.protobuf.javame.input.taghandler.UnknownTagHandler;
import net.jarlehansen.protobuf.javame.input.taghandler.DefaultUnknownTagHandlerImpl;

public final class sc_lack_infos extends AbstractOutputWriter {
	private static UnknownTagHandler unknownTagHandler = DefaultUnknownTagHandlerImpl.newInstance();

	private final java.util.Vector infos;
	private static final int fieldNumberInfos = 1;


	public static Builder newBuilder() {
		return new Builder();
	}

	private sc_lack_infos(final Builder builder) {
			this.infos = builder.infos;
			}

	public static class Builder {
		private java.util.Vector infos = new java.util.Vector();
		private boolean hasInfos = false;


		private Builder() {
		}

		public Builder setInfos(final java.util.Vector infos) {
			if(!hasInfos) {
				hasInfos = true;
			}
			this.infos = infos;
			return this;
		}


		public Builder addElementInfos(final st_lack_info element) {
			if(!hasInfos) {
				hasInfos = true;
			}
			infos.addElement(element);
			return this;
		}

		public sc_lack_infos build() {
			return new sc_lack_infos(this);
		}
	}

	public java.util.Vector getInfos() {
		return infos;
	}

	public String toString() {
		final String TAB = "   ";
		String retValue = "";
		retValue += this.getClass().getName() + "(";
		retValue += "infos = " + this.infos + TAB;
		retValue += ")";

		return retValue;
	}

	// Override
	public int computeSize() {
		int totalSize = 0;
		totalSize += computeNestedMessageSize();

		return totalSize;
	}

	private int computeNestedMessageSize() {
		int messageSize = 0;
		messageSize += ComputeSizeUtil.computeListSize(fieldNumberInfos, net.jarlehansen.protobuf.javame.SupportedDataTypes.DATA_TYPE_CUSTOM, infos);

		return messageSize;
	}

	// Override
	public void writeFields(final OutputWriter writer) throws IOException {
		writer.writeList(fieldNumberInfos, net.jarlehansen.protobuf.javame.SupportedDataTypes.DATA_TYPE_CUSTOM, infos);
	}

	static sc_lack_infos parseFields(final InputReader reader) throws IOException {
		int nextFieldNumber = getNextFieldNumber(reader);
		final sc_lack_infos.Builder builder = sc_lack_infos.newBuilder();

		while (nextFieldNumber > 0) {
			if(!populateBuilderWithField(reader, builder, nextFieldNumber)) {
				reader.getPreviousTagDataTypeAndReadContent();
			}
			nextFieldNumber = getNextFieldNumber(reader);
		}

		return builder.build();
	}

	static int getNextFieldNumber(final InputReader reader) throws IOException {
		return reader.getNextFieldNumber();
	}

	static boolean populateBuilderWithField(final InputReader reader, final Builder builder, final int fieldNumber) throws IOException {
		boolean fieldFound = true;
		switch (fieldNumber) {
			case fieldNumberInfos:
			 java.util.Vector vcInfos = reader.readMessages(fieldNumberInfos);
				for(int i = 0 ; i < vcInfos.size(); i++) {
					byte[] eachBinData = (byte[]) vcInfos.elementAt(i);
					st_lack_info.Builder builderInfos = st_lack_info.newBuilder();
					InputReader innerInputReader = new InputReader(eachBinData, unknownTagHandler);
					boolean boolInfos = true;
					int nestedFieldInfos = -1;
					while(boolInfos) {
						nestedFieldInfos = getNextFieldNumber(innerInputReader);
						boolInfos = st_lack_info.populateBuilderWithField(innerInputReader, builderInfos, nestedFieldInfos);
					}
					eachBinData = null;
					innerInputReader = null;
					builder.addElementInfos(builderInfos.build());
				}
				break;
		default:
			fieldFound = false;
		}
		return fieldFound;
	}

	public static void setUnknownTagHandler(final UnknownTagHandler unknownTagHandler) {
		sc_lack_infos.unknownTagHandler = unknownTagHandler;
	}

	public static sc_lack_infos parseFrom(final byte[] data) throws IOException {
		return parseFields(new InputReader(data, unknownTagHandler));
	}

	public static sc_lack_infos parseFrom(final InputStream inputStream) throws IOException {
		return parseFields(new InputReader(inputStream, unknownTagHandler));
	}

	public static sc_lack_infos parseDelimitedFrom(final InputStream inputStream) throws IOException {
		final int limit = DelimitedSizeUtil.readDelimitedSize(inputStream);
		return parseFields(new InputReader(new DelimitedInputStream(inputStream, limit), unknownTagHandler));
	}
}