package protocol;
// Generated by proto2javame, Wed Jan 13 00:12:46 CST 2016.

import java.io.IOException;
import java.io.InputStream;


import net.jarlehansen.protobuf.javame.input.InputReader;
import net.jarlehansen.protobuf.javame.input.DelimitedInputStream;
import net.jarlehansen.protobuf.javame.input.DelimitedSizeUtil;
import net.jarlehansen.protobuf.javame.ComputeSizeUtil;
import net.jarlehansen.protobuf.javame.output.OutputWriter;
import net.jarlehansen.protobuf.javame.AbstractOutputWriter;
import net.jarlehansen.protobuf.javame.input.taghandler.UnknownTagHandler;
import net.jarlehansen.protobuf.javame.input.taghandler.DefaultUnknownTagHandlerImpl;

public final class st_fee extends AbstractOutputWriter {
	private static UnknownTagHandler unknownTagHandler = DefaultUnknownTagHandlerImpl.newInstance();

	private final int fee_id;
	private static final int fieldNumberFee_id = 1;
	private final boolean hasFee_id;

	private final String phone_number;
	private static final int fieldNumberPhone_number = 2;
	private final boolean hasPhone_number;

	private final int time;
	private static final int fieldNumberTime = 3;
	private final boolean hasTime;

	private final int status;
	private static final int fieldNumberStatus = 4;
	private final boolean hasStatus;


	public static Builder newBuilder() {
		return new Builder();
	}

	private st_fee(final Builder builder) {
			this.fee_id = builder.fee_id;
			this.hasFee_id = builder.hasFee_id;
			this.phone_number = builder.phone_number;
			this.hasPhone_number = builder.hasPhone_number;
			this.time = builder.time;
			this.hasTime = builder.hasTime;
			this.status = builder.status;
			this.hasStatus = builder.hasStatus;
			}

	public static class Builder {
		private int fee_id;
		private boolean hasFee_id = false;

		private String phone_number;
		private boolean hasPhone_number = false;

		private int time;
		private boolean hasTime = false;

		private int status;
		private boolean hasStatus = false;


		private Builder() {
		}

		public Builder setFee_id(final int fee_id) {
			this.fee_id = fee_id;
			this.hasFee_id = true;
			return this;
		}

		public Builder setPhone_number(final String phone_number) {
			this.phone_number = phone_number;
			this.hasPhone_number = true;
			return this;
		}

		public Builder setTime(final int time) {
			this.time = time;
			this.hasTime = true;
			return this;
		}

		public Builder setStatus(final int status) {
			this.status = status;
			this.hasStatus = true;
			return this;
		}

		public st_fee build() {
			return new st_fee(this);
		}
	}

	public int getFee_id() {
		return fee_id;
	}

	public boolean hasFee_id() {
		return hasFee_id;
	}

	public String getPhone_number() {
		return phone_number;
	}

	public boolean hasPhone_number() {
		return hasPhone_number;
	}

	public int getTime() {
		return time;
	}

	public boolean hasTime() {
		return hasTime;
	}

	public int getStatus() {
		return status;
	}

	public boolean hasStatus() {
		return hasStatus;
	}

	public String toString() {
		final String TAB = "   ";
		String retValue = "";
		retValue += this.getClass().getName() + "(";
		if(hasFee_id) retValue += "fee_id = " + this.fee_id + TAB;
		if(hasPhone_number) retValue += "phone_number = " + this.phone_number + TAB;
		if(hasTime) retValue += "time = " + this.time + TAB;
		if(hasStatus) retValue += "status = " + this.status + TAB;
		retValue += ")";

		return retValue;
	}

	// Override
	public int computeSize() {
		int totalSize = 0;
		if(hasFee_id) totalSize += ComputeSizeUtil.computeIntSize(fieldNumberFee_id, fee_id);
		if(hasPhone_number) totalSize += ComputeSizeUtil.computeStringSize(fieldNumberPhone_number, phone_number);
		if(hasTime) totalSize += ComputeSizeUtil.computeIntSize(fieldNumberTime, time);
		if(hasStatus) totalSize += ComputeSizeUtil.computeIntSize(fieldNumberStatus, status);
		totalSize += computeNestedMessageSize();

		return totalSize;
	}

	private int computeNestedMessageSize() {
		int messageSize = 0;

		return messageSize;
	}

	// Override
	public void writeFields(final OutputWriter writer) throws IOException {
		if(hasFee_id) writer.writeInt(fieldNumberFee_id, fee_id);
		if(hasPhone_number) writer.writeString(fieldNumberPhone_number, phone_number);
		if(hasTime) writer.writeInt(fieldNumberTime, time);
		if(hasStatus) writer.writeInt(fieldNumberStatus, status);
	}

	static st_fee parseFields(final InputReader reader) throws IOException {
		int nextFieldNumber = getNextFieldNumber(reader);
		final st_fee.Builder builder = st_fee.newBuilder();

		while (nextFieldNumber > 0) {
			if(!populateBuilderWithField(reader, builder, nextFieldNumber)) {
				reader.getPreviousTagDataTypeAndReadContent();
			}
			nextFieldNumber = getNextFieldNumber(reader);
		}

		return builder.build();
	}

	static int getNextFieldNumber(final InputReader reader) throws IOException {
		return reader.getNextFieldNumber();
	}

	static boolean populateBuilderWithField(final InputReader reader, final Builder builder, final int fieldNumber) throws IOException {
		boolean fieldFound = true;
		switch (fieldNumber) {
			case fieldNumberFee_id:
				builder.setFee_id(reader.readInt(fieldNumber));
				break;
			case fieldNumberPhone_number:
				builder.setPhone_number(reader.readString(fieldNumber));
				break;
			case fieldNumberTime:
				builder.setTime(reader.readInt(fieldNumber));
				break;
			case fieldNumberStatus:
				builder.setStatus(reader.readInt(fieldNumber));
				break;
		default:
			fieldFound = false;
		}
		return fieldFound;
	}

	public static void setUnknownTagHandler(final UnknownTagHandler unknownTagHandler) {
		st_fee.unknownTagHandler = unknownTagHandler;
	}

	public static st_fee parseFrom(final byte[] data) throws IOException {
		return parseFields(new InputReader(data, unknownTagHandler));
	}

	public static st_fee parseFrom(final InputStream inputStream) throws IOException {
		return parseFields(new InputReader(inputStream, unknownTagHandler));
	}

	public static st_fee parseDelimitedFrom(final InputStream inputStream) throws IOException {
		final int limit = DelimitedSizeUtil.readDelimitedSize(inputStream);
		return parseFields(new InputReader(new DelimitedInputStream(inputStream, limit), unknownTagHandler));
	}
}