package protocol;
// Generated by proto2javame, Wed Jan 13 00:12:46 CST 2016.

import java.io.IOException;
import java.io.InputStream;


import net.jarlehansen.protobuf.javame.input.InputReader;
import net.jarlehansen.protobuf.javame.input.DelimitedInputStream;
import net.jarlehansen.protobuf.javame.input.DelimitedSizeUtil;
import net.jarlehansen.protobuf.javame.ComputeSizeUtil;
import net.jarlehansen.protobuf.javame.output.OutputWriter;
import net.jarlehansen.protobuf.javame.AbstractOutputWriter;
import net.jarlehansen.protobuf.javame.input.taghandler.UnknownTagHandler;
import net.jarlehansen.protobuf.javame.input.taghandler.DefaultUnknownTagHandlerImpl;

public final class t_mylog extends AbstractOutputWriter {
	private static UnknownTagHandler unknownTagHandler = DefaultUnknownTagHandlerImpl.newInstance();

	private final int id;
	private static final int fieldNumberId = 1;
	private final boolean hasId;

	private final int time;
	private static final int fieldNumberTime = 2;
	private final boolean hasTime;

	private final int itemid;
	private static final int fieldNumberItemid = 3;
	private final boolean hasItemid;


	public static Builder newBuilder() {
		return new Builder();
	}

	private t_mylog(final Builder builder) {
			this.id = builder.id;
			this.hasId = builder.hasId;
			this.time = builder.time;
			this.hasTime = builder.hasTime;
			this.itemid = builder.itemid;
			this.hasItemid = builder.hasItemid;
			}

	public static class Builder {
		private int id;
		private boolean hasId = false;

		private int time;
		private boolean hasTime = false;

		private int itemid;
		private boolean hasItemid = false;


		private Builder() {
		}

		public Builder setId(final int id) {
			this.id = id;
			this.hasId = true;
			return this;
		}

		public Builder setTime(final int time) {
			this.time = time;
			this.hasTime = true;
			return this;
		}

		public Builder setItemid(final int itemid) {
			this.itemid = itemid;
			this.hasItemid = true;
			return this;
		}

		public t_mylog build() {
			return new t_mylog(this);
		}
	}

	public int getId() {
		return id;
	}

	public boolean hasId() {
		return hasId;
	}

	public int getTime() {
		return time;
	}

	public boolean hasTime() {
		return hasTime;
	}

	public int getItemid() {
		return itemid;
	}

	public boolean hasItemid() {
		return hasItemid;
	}

	public String toString() {
		final String TAB = "   ";
		String retValue = "";
		retValue += this.getClass().getName() + "(";
		if(hasId) retValue += "id = " + this.id + TAB;
		if(hasTime) retValue += "time = " + this.time + TAB;
		if(hasItemid) retValue += "itemid = " + this.itemid + TAB;
		retValue += ")";

		return retValue;
	}

	// Override
	public int computeSize() {
		int totalSize = 0;
		if(hasId) totalSize += ComputeSizeUtil.computeIntSize(fieldNumberId, id);
		if(hasTime) totalSize += ComputeSizeUtil.computeIntSize(fieldNumberTime, time);
		if(hasItemid) totalSize += ComputeSizeUtil.computeIntSize(fieldNumberItemid, itemid);
		totalSize += computeNestedMessageSize();

		return totalSize;
	}

	private int computeNestedMessageSize() {
		int messageSize = 0;

		return messageSize;
	}

	// Override
	public void writeFields(final OutputWriter writer) throws IOException {
		if(hasId) writer.writeInt(fieldNumberId, id);
		if(hasTime) writer.writeInt(fieldNumberTime, time);
		if(hasItemid) writer.writeInt(fieldNumberItemid, itemid);
	}

	static t_mylog parseFields(final InputReader reader) throws IOException {
		int nextFieldNumber = getNextFieldNumber(reader);
		final t_mylog.Builder builder = t_mylog.newBuilder();

		while (nextFieldNumber > 0) {
			if(!populateBuilderWithField(reader, builder, nextFieldNumber)) {
				reader.getPreviousTagDataTypeAndReadContent();
			}
			nextFieldNumber = getNextFieldNumber(reader);
		}

		return builder.build();
	}

	static int getNextFieldNumber(final InputReader reader) throws IOException {
		return reader.getNextFieldNumber();
	}

	static boolean populateBuilderWithField(final InputReader reader, final Builder builder, final int fieldNumber) throws IOException {
		boolean fieldFound = true;
		switch (fieldNumber) {
			case fieldNumberId:
				builder.setId(reader.readInt(fieldNumber));
				break;
			case fieldNumberTime:
				builder.setTime(reader.readInt(fieldNumber));
				break;
			case fieldNumberItemid:
				builder.setItemid(reader.readInt(fieldNumber));
				break;
		default:
			fieldFound = false;
		}
		return fieldFound;
	}

	public static void setUnknownTagHandler(final UnknownTagHandler unknownTagHandler) {
		t_mylog.unknownTagHandler = unknownTagHandler;
	}

	public static t_mylog parseFrom(final byte[] data) throws IOException {
		return parseFields(new InputReader(data, unknownTagHandler));
	}

	public static t_mylog parseFrom(final InputStream inputStream) throws IOException {
		return parseFields(new InputReader(inputStream, unknownTagHandler));
	}

	public static t_mylog parseDelimitedFrom(final InputStream inputStream) throws IOException {
		final int limit = DelimitedSizeUtil.readDelimitedSize(inputStream);
		return parseFields(new InputReader(new DelimitedInputStream(inputStream, limit), unknownTagHandler));
	}
}