package protocol;
// Generated by proto2javame, Sat Jan 09 02:23:16 CST 2016.

import java.io.IOException;
import java.io.InputStream;


import net.jarlehansen.protobuf.javame.input.InputReader;
import net.jarlehansen.protobuf.javame.input.DelimitedInputStream;
import net.jarlehansen.protobuf.javame.input.DelimitedSizeUtil;
import net.jarlehansen.protobuf.javame.ComputeSizeUtil;
import net.jarlehansen.protobuf.javame.output.OutputWriter;
import net.jarlehansen.protobuf.javame.AbstractOutputWriter;
import net.jarlehansen.protobuf.javame.input.taghandler.UnknownTagHandler;
import net.jarlehansen.protobuf.javame.input.taghandler.DefaultUnknownTagHandlerImpl;

public final class sc_enter_place extends AbstractOutputWriter {
	private static UnknownTagHandler unknownTagHandler = DefaultUnknownTagHandlerImpl.newInstance();

	private final String host;
	private static final int fieldNumberHost = 1;
	private final boolean hasHost;

	private final int port;
	private static final int fieldNumberPort = 2;
	private final boolean hasPort;


	public static Builder newBuilder() {
		return new Builder();
	}

	private sc_enter_place(final Builder builder) {
			this.host = builder.host;
			this.hasHost = builder.hasHost;
			this.port = builder.port;
			this.hasPort = builder.hasPort;
			}

	public static class Builder {
		private String host;
		private boolean hasHost = false;

		private int port;
		private boolean hasPort = false;


		private Builder() {
		}

		public Builder setHost(final String host) {
			this.host = host;
			this.hasHost = true;
			return this;
		}

		public Builder setPort(final int port) {
			this.port = port;
			this.hasPort = true;
			return this;
		}

		public sc_enter_place build() {
			return new sc_enter_place(this);
		}
	}

	public String getHost() {
		return host;
	}

	public boolean hasHost() {
		return hasHost;
	}

	public int getPort() {
		return port;
	}

	public boolean hasPort() {
		return hasPort;
	}

	public String toString() {
		final String TAB = "   ";
		String retValue = "";
		retValue += this.getClass().getName() + "(";
		if(hasHost) retValue += "host = " + this.host + TAB;
		if(hasPort) retValue += "port = " + this.port + TAB;
		retValue += ")";

		return retValue;
	}

	// Override
	public int computeSize() {
		int totalSize = 0;
		if(hasHost) totalSize += ComputeSizeUtil.computeStringSize(fieldNumberHost, host);
		if(hasPort) totalSize += ComputeSizeUtil.computeIntSize(fieldNumberPort, port);
		totalSize += computeNestedMessageSize();

		return totalSize;
	}

	private int computeNestedMessageSize() {
		int messageSize = 0;

		return messageSize;
	}

	// Override
	public void writeFields(final OutputWriter writer) throws IOException {
		if(hasHost) writer.writeString(fieldNumberHost, host);
		if(hasPort) writer.writeInt(fieldNumberPort, port);
	}

	static sc_enter_place parseFields(final InputReader reader) throws IOException {
		int nextFieldNumber = getNextFieldNumber(reader);
		final sc_enter_place.Builder builder = sc_enter_place.newBuilder();

		while (nextFieldNumber > 0) {
			if(!populateBuilderWithField(reader, builder, nextFieldNumber)) {
				reader.getPreviousTagDataTypeAndReadContent();
			}
			nextFieldNumber = getNextFieldNumber(reader);
		}

		return builder.build();
	}

	static int getNextFieldNumber(final InputReader reader) throws IOException {
		return reader.getNextFieldNumber();
	}

	static boolean populateBuilderWithField(final InputReader reader, final Builder builder, final int fieldNumber) throws IOException {
		boolean fieldFound = true;
		switch (fieldNumber) {
			case fieldNumberHost:
				builder.setHost(reader.readString(fieldNumber));
				break;
			case fieldNumberPort:
				builder.setPort(reader.readInt(fieldNumber));
				break;
		default:
			fieldFound = false;
		}
		return fieldFound;
	}

	public static void setUnknownTagHandler(final UnknownTagHandler unknownTagHandler) {
		sc_enter_place.unknownTagHandler = unknownTagHandler;
	}

	public static sc_enter_place parseFrom(final byte[] data) throws IOException {
		return parseFields(new InputReader(data, unknownTagHandler));
	}

	public static sc_enter_place parseFrom(final InputStream inputStream) throws IOException {
		return parseFields(new InputReader(inputStream, unknownTagHandler));
	}

	public static sc_enter_place parseDelimitedFrom(final InputStream inputStream) throws IOException {
		final int limit = DelimitedSizeUtil.readDelimitedSize(inputStream);
		return parseFields(new InputReader(new DelimitedInputStream(inputStream, limit), unknownTagHandler));
	}
}