package protocol;
// Generated by proto2javame, Sat Jan 09 02:23:16 CST 2016.

import java.io.IOException;
import java.io.InputStream;


import net.jarlehansen.protobuf.javame.input.InputReader;
import net.jarlehansen.protobuf.javame.input.DelimitedInputStream;
import net.jarlehansen.protobuf.javame.input.DelimitedSizeUtil;
import net.jarlehansen.protobuf.javame.ComputeSizeUtil;
import net.jarlehansen.protobuf.javame.output.OutputWriter;
import net.jarlehansen.protobuf.javame.AbstractOutputWriter;
import net.jarlehansen.protobuf.javame.input.taghandler.UnknownTagHandler;
import net.jarlehansen.protobuf.javame.input.taghandler.DefaultUnknownTagHandlerImpl;

public final class sc_friend_watch extends AbstractOutputWriter {
	private static UnknownTagHandler unknownTagHandler = DefaultUnknownTagHandlerImpl.newInstance();

	private final boolean result;
	private static final int fieldNumberResult = 1;
	private final boolean hasResult;

	private final int reason;
	private static final int fieldNumberReason = 2;
	private final boolean hasReason;

	private final boolean watch;
	private static final int fieldNumberWatch = 3;
	private final boolean hasWatch;

	private final String id;
	private static final int fieldNumberId = 4;
	private final boolean hasId;

	private final String idtype;
	private static final int fieldNumberIdtype = 5;
	private final boolean hasIdtype;


	public static Builder newBuilder() {
		return new Builder();
	}

	private sc_friend_watch(final Builder builder) {
			this.result = builder.result;
			this.hasResult = builder.hasResult;
			this.reason = builder.reason;
			this.hasReason = builder.hasReason;
			this.watch = builder.watch;
			this.hasWatch = builder.hasWatch;
			this.id = builder.id;
			this.hasId = builder.hasId;
			this.idtype = builder.idtype;
			this.hasIdtype = builder.hasIdtype;
			}

	public static class Builder {
		private boolean result;
		private boolean hasResult = false;

		private int reason;
		private boolean hasReason = false;

		private boolean watch;
		private boolean hasWatch = false;

		private String id;
		private boolean hasId = false;

		private String idtype;
		private boolean hasIdtype = false;


		private Builder() {
		}

		public Builder setResult(final boolean result) {
			this.result = result;
			this.hasResult = true;
			return this;
		}

		public Builder setReason(final int reason) {
			this.reason = reason;
			this.hasReason = true;
			return this;
		}

		public Builder setWatch(final boolean watch) {
			this.watch = watch;
			this.hasWatch = true;
			return this;
		}

		public Builder setId(final String id) {
			this.id = id;
			this.hasId = true;
			return this;
		}

		public Builder setIdtype(final String idtype) {
			this.idtype = idtype;
			this.hasIdtype = true;
			return this;
		}

		public sc_friend_watch build() {
			return new sc_friend_watch(this);
		}
	}

	public boolean getResult() {
		return result;
	}

	public boolean hasResult() {
		return hasResult;
	}

	public int getReason() {
		return reason;
	}

	public boolean hasReason() {
		return hasReason;
	}

	public boolean getWatch() {
		return watch;
	}

	public boolean hasWatch() {
		return hasWatch;
	}

	public String getId() {
		return id;
	}

	public boolean hasId() {
		return hasId;
	}

	public String getIdtype() {
		return idtype;
	}

	public boolean hasIdtype() {
		return hasIdtype;
	}

	public String toString() {
		final String TAB = "   ";
		String retValue = "";
		retValue += this.getClass().getName() + "(";
		if(hasResult) retValue += "result = " + this.result + TAB;
		if(hasReason) retValue += "reason = " + this.reason + TAB;
		if(hasWatch) retValue += "watch = " + this.watch + TAB;
		if(hasId) retValue += "id = " + this.id + TAB;
		if(hasIdtype) retValue += "idtype = " + this.idtype + TAB;
		retValue += ")";

		return retValue;
	}

	// Override
	public int computeSize() {
		int totalSize = 0;
		if(hasResult) totalSize += ComputeSizeUtil.computeBooleanSize(fieldNumberResult, result);
		if(hasReason) totalSize += ComputeSizeUtil.computeIntSize(fieldNumberReason, reason);
		if(hasWatch) totalSize += ComputeSizeUtil.computeBooleanSize(fieldNumberWatch, watch);
		if(hasId) totalSize += ComputeSizeUtil.computeStringSize(fieldNumberId, id);
		if(hasIdtype) totalSize += ComputeSizeUtil.computeStringSize(fieldNumberIdtype, idtype);
		totalSize += computeNestedMessageSize();

		return totalSize;
	}

	private int computeNestedMessageSize() {
		int messageSize = 0;

		return messageSize;
	}

	// Override
	public void writeFields(final OutputWriter writer) throws IOException {
		if(hasResult) writer.writeBoolean(fieldNumberResult, result);
		if(hasReason) writer.writeInt(fieldNumberReason, reason);
		if(hasWatch) writer.writeBoolean(fieldNumberWatch, watch);
		if(hasId) writer.writeString(fieldNumberId, id);
		if(hasIdtype) writer.writeString(fieldNumberIdtype, idtype);
	}

	static sc_friend_watch parseFields(final InputReader reader) throws IOException {
		int nextFieldNumber = getNextFieldNumber(reader);
		final sc_friend_watch.Builder builder = sc_friend_watch.newBuilder();

		while (nextFieldNumber > 0) {
			if(!populateBuilderWithField(reader, builder, nextFieldNumber)) {
				reader.getPreviousTagDataTypeAndReadContent();
			}
			nextFieldNumber = getNextFieldNumber(reader);
		}

		return builder.build();
	}

	static int getNextFieldNumber(final InputReader reader) throws IOException {
		return reader.getNextFieldNumber();
	}

	static boolean populateBuilderWithField(final InputReader reader, final Builder builder, final int fieldNumber) throws IOException {
		boolean fieldFound = true;
		switch (fieldNumber) {
			case fieldNumberResult:
				builder.setResult(reader.readBoolean(fieldNumber));
				break;
			case fieldNumberReason:
				builder.setReason(reader.readInt(fieldNumber));
				break;
			case fieldNumberWatch:
				builder.setWatch(reader.readBoolean(fieldNumber));
				break;
			case fieldNumberId:
				builder.setId(reader.readString(fieldNumber));
				break;
			case fieldNumberIdtype:
				builder.setIdtype(reader.readString(fieldNumber));
				break;
		default:
			fieldFound = false;
		}
		return fieldFound;
	}

	public static void setUnknownTagHandler(final UnknownTagHandler unknownTagHandler) {
		sc_friend_watch.unknownTagHandler = unknownTagHandler;
	}

	public static sc_friend_watch parseFrom(final byte[] data) throws IOException {
		return parseFields(new InputReader(data, unknownTagHandler));
	}

	public static sc_friend_watch parseFrom(final InputStream inputStream) throws IOException {
		return parseFields(new InputReader(inputStream, unknownTagHandler));
	}

	public static sc_friend_watch parseDelimitedFrom(final InputStream inputStream) throws IOException {
		final int limit = DelimitedSizeUtil.readDelimitedSize(inputStream);
		return parseFields(new InputReader(new DelimitedInputStream(inputStream, limit), unknownTagHandler));
	}
}